# Generated by Django 3.1.3 on 2020-11-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201104_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
